package com.example.springdemo

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
//import org.springframework.web.bind.annotation.GetMapping
//import org.springframework.web.bind.annotation.RestController


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
class SpringdemoApplication

//@RestController
//class HelloController{
//	@GetMapping("/")
//	fun hello(): String {
//		return "Hello Spring-Boot 555"
//	}
//}

fun main(args: Array<String>) {
	runApplication<SpringdemoApplication>(*args)
}
